version: '3.7'
services:
  template-db:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: ${DB_INIT_DB}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - template-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  template-dbadmin:
    image: dpage/pgadmin4:4.25
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASS}
      PGADMIN_LISTEN_PORT: ${DB_ADMIN_GUEST_PORT}
    ports:
      - ${DB_ADMIN_HOST_PORT}:${DB_ADMIN_GUEST_PORT}
    volumes:
      - template-dbadmin-data:/var/lib/pgadmin
    depends_on:
      - template-db
  app:
    image: caramelpointdr/template:${TEMPLATE_IMAGE_VERSION}
    expose:
      - '80'
    ports:
      - '80:3000'
    depends_on:
      - template-db
volumes:
  template-db-data:
  template-dbadmin-data: